### ISSUE TITLE
UserSig verification Failed. The UserSig in use maybe generated by Secret Key from other SDKAppID. Please regenerate UserSig by Secret Key from its own SDKAppID

### ISSUE THREAD

**Issue by sulongstudio** [TencentCloud/tencentcloud-im-sdk-java#3]
![图片](https://user-images.githubusercontent.com/111841847/190682403-2cbfbdea-9c4d-4f47-8322-af39a52c9f92.png)
![图片](https://user-images.githubusercontent.com/111841847/190682443-3c9a63f7-1ad9-4f55-94a2-c623bc1416e3.png)

`class AccountCheckResponse {
    actionStatus: FAIL
    errorInfo: UserSig verification Failed. The UserSig in use maybe generated by Secret Key from other SDKAppID. Please regenerate UserSig by Secret Key from its own SDKAppID.
    errorCode: 70009
    resultItem: null
    additionalProperties: null
}`

**Comment by shifpeng** [comment]
这里的key你是不是搞错了，用的是控制台上的密钥
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/25630686/193176521-ac9f1560-6484-458d-aea6-fed9d1844089.png">

如果还有问题，项目介绍有交流群链接，可以进群反馈问题
